name: Add Data to Firestore

on:
  schedule:
    # 15분 간격으로 실행
    - cron: '*/15 * * * *'
  workflow_dispatch:


jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
             
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r ./rpas/requirements.txt

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "serviceAccount.json"
          json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Add data to Firestore
        run: |
          python ./rpas/add_data_to_firestore.py
          python ./rpas/add_data_to_firestore_v2.py
        env:
          END_POINT: ${{ secrets.END_POINT }}
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}

          